### ISSUE TITLE
FR: Playlist Support

### ISSUE THREAD

**Issue by r1cht3r** [jellyfin-archive/jellyfin-roku-legacy#108]
Playlists are supported by the webapp and other clients, but return unknown media type in jellyfin-roku.

**Comment by bryce-hoehn** [comment]
When I try to access the playlist library on my Roku all I get is an error message saying "This UserView contains no items"

**Comment by neilsb** [comment]
There was an update to the Grid View, so that it can now open (I think) all types, but will only show items that it knows how to play.  Since it can't handle playlists yet, you will see the message that it contains no items.   We should perhaps change it to say "...contain no compatible items" until we get playlist support in place.

**Comment by cewert** [comment]
> We should perhaps change it to say "...contain no compatible items" until we get playlist support in place.

@neilsb  What's your thoughts on this now with basic music support on the way in #597? A lot of people use playlists for music. Would it be as simple as hiding the Playlists library from the My Media row?

**Comment by saith89** [comment]
I would like playlists for shows. I sometimes don't know what to watch, so I put all my sitcoms into a playlist, hoping I could shuffle play them on the TV, but it doesn't work on my Roku

**Comment by czadikem** [comment]
Any eta of when this will be added?

**Comment by 1hitsong** [comment]
> Any eta of when this will be added?

Nope. The best I can offer is "When it's ready for release."
