### ISSUE TITLE
Roku Jellyfin App Missing Additional Parts Selection

### ISSUE THREAD

**Issue by Joep2023** [jellyfin-archive/jellyfin-roku-legacy#1244]
**Server System (please complete the following information):**
 - OS: [Roku]
 - Jellyfin Version: [1.5 Build 0]
 
**Client System (please complete the following information):**
 - Device: [Roku]

Roku app does not display Additional Parts option. For example Ben Hur movie is divided into 2 parts. Second part is not available for selection. Jellyfin app on an Android phone displays this option for selection of the second part of the movie.

**Comment by jimdogx** [comment]
Did it not show up if you scrolled down?  We added an additional parts section back in December:

https://github.com/jellyfin/jellyfin-roku/pull/857

I'm wondering if it is now broken?

**Comment by cewert** [comment]
> Jellyfin Version: [1.5 Build 0]

I'm assuming that's your roku app's version since the server started at version 10.0. Is there a reason for not upgrading to the latest stable version of the app? The latest release on the roku store is 1.6.6

**Comment by jimdogx** [comment]
Good catch @cewert, I totally missed the reported app version.

@Joep2023 Additional parts was added in version 1.6.1 of the app.

**Comment by Goldfish8996** [comment]
I am having this same issue, but I am on Roku Version 1.6
I deleted and redownloaded the app on the Roku store, but it still says version 1.6
I'm not sure if there is a reason I'm not able to download the most up to date version, or that it is simply not showing if it is version 1.6.1 or 1.6.2 or 1.6.0, etc.

**Comment by cewert** [comment]
@Goldfish8996 roku makes this confusing. They call the last number the "build" and show it separately from the version number. So if you hit * on the latest version of the Jellyfin channel from the home screen, you will see `version 1.6 build 6` instead of `version 1.6.6`.

The Additional Parts feature mentioned in this issue was first released in v1.6.2

**Comment by Goldfish8996** [comment]
@cewert Thanks for the tip! I can now confirm I am running 1.6 build 6 on the Roku. My problem may be stemming from the fact that I am unable to find the Additional Parts for Shows instead of for Movies. Each episode stands on it's own in the season, and I have an Additional Part for each episode, so there is no way open the same "Cast and Crew" type menu for one specific episode, but instead for the whole season. Am I missing something or has this not been addressed yet?

**Comment by cewert** [comment]
@Goldfish8996 The PR linked in this issue only added Additional Parts for Movies - #857. So currently your use case is not supported. Feel free to open a new issue to add support for TV.

If you are desperate you could try the following as a workaround. Play one of the episodes that has additional parts and then pause it. Go to the home screen and locate the episode under the "Continue Watching" row. Hit "OK" on the episode and select the bottom option "Go to episode". This will open the episode using the "Movie detail" view and possibly allow you to see the "additional parts". Or it might just be a buggy mess and crash 🤷
