### ISSUE TITLE
Respect Maximum Transcoding Resolution user setting

### ISSUE THREAD

**Issue by entropicdrifter** [jellyfin-archive/jellyfin-roku-legacy#1348]
## Describe the feature you'd like
When my Roku Streaming Stick+ transcodes video, it requests the transcoded video to be in the original resolution. My server is somewhat underpowered, so I'd prefer if my transcodes are never over 1080p. 

There exists a user-level setting for maximum transcode resolution, which I've set, but the Roku doesn't respect this setting.

It would also be fine to have a maximum transcode resolution setting in the Roku app itself, if that's easier to implement.

## Additional context
My TV is 1080p, but the Streaming Stick+ can play back 4K files on it just fine by downscaling on the client side. Unfortunately, HDR files need tonemapping. My underpowered server can tonemap when scaling down to 1080p at ~36 FPS, but when trying to maintain the full 4K resolution it slows down to ~16 FPS. If I had a way to tell the Roku to request the video in 1080p or lower resolution whenever it's transcoding, it would be much more convenient than trying to maintain HDR and SDR copies of my 4K content.

**Comment by cewert** [comment]
I'm working on a PR that would fix your issue (#1299) but without adding support for the web client setting.

The web client setting you mentioned is currently unavailable to for us to access while using the API (it's only saved locally in the browser). Instead I've made a client side user setting that defaults to using the connected TVs resolution. This can also be turned off for users that would rather send the full video even when the attached TV doesn't support the resolution.

I'm going to tag this issue as `upstream` since we can't implement the setting how you requested. I'll also close this issue once #1299 gets merged. If you'd prefer to keep the issue open as a reminder to implement the web client setting once it's available on the API, that's fine. Just give me a shout or feel free to reopen after #1299 is merged.

**Comment by entropicdrifter** [comment]
That works for me, though in my particular case it might be a bit arduous since 2160p files that are SDR don't need to transcode, but I can just flip the setting off when that's the case if I want to preserve full quality by letting the Roku downscale when possible

**Comment by cewert** [comment]
I figured out how to restrict playback resolution for only transcoded files in #1299 🎉

I've added a user setting that allows the user to restrict resolution for all files or just transcoded files. Defaults to just transcoded files.
The other Maximum Resolution setting remains and is applied to either the Codec Profile or TranscodingProfile depending on what mode is set in settings (but only when the max res setting <> "off")

NOTE: The transcoding reason "The videos' resolution is not supported" will only show up when the mode is set to everything. transcoding mode will not show a transcoding reason but can be observed by checking the ffmpeg log.

Does that satisfy your requirements? Anything else you can think to add?

**Comment by entropicdrifter** [comment]
That's perfect! With that change I'd always get the best possible quality on my setup!
