### ISSUE TITLE
Filenames to match component names

### ISSUE THREAD

**Issue by neilsb** [jellyfin-archive/jellyfin-roku-legacy#142]
Having Filenames match component names would useful from a development point of view.  

In many cases the component name is slightly different (and in some quite different) which just adds an additional step when trying to find the appropriate area of code; especially when you're not familiar with the code base.

Examples
-  **MovieItemMinimal** in _minimal-details.xml_
-  **MovieData** in _movie.xml_
-  **OptionsSlider** in _panel.xml_

It would also help for new developers if there was a standard for naming files (e.g.   "search-results.xml" or "SearchResults.xml") - Again there seems to be a mix at the current time.

**Comment by neilsb** [comment]
I'm happy to look into this - but would first need guidance if this is something that would be useful - and what the _standards_ should be.

**Comment by cewert** [comment]
I don't know about BrightScript standards but having the file name match the component name makes a lot of sense to me. :+1:

**Comment by bisby** [comment]
That sounds good. There was definitely an effort to standardize stuff. but as things went around... the standard changed without retroactively changing stuff.

I would be fine with someone setting a standard, either based on BrightScript suggestions or just demanding something. I'm the one who most likely caused the problems in the first place, so I'll try to not be too opinionated here since I clearly can't make up my mind.

**Comment by neilsb** [comment]
I've had a look about, but don't see anything on standards for file naming for brightscript / roku.  

Since the majority of component names are already PascalCase, I would propose that this becomes the standard, and the files should be named the same as the component (with the .xml or .brs suffixes)

Although brightscript is (on the whole) not case sensitive I would suggest that the filenames should also be PascalCase, just for consistency.
