### ISSUE TITLE
pause menu and next up button dont play nicely

### ISSUE THREAD

**Issue by sevenrats** [jellyfin-archive/jellyfin-roku-legacy#1511]
skip forward to the "Next Episode" interval with the right arrow key.  Pause menu disappears and next up button appears, but next up button doesn't have focus.

**Comment by cewert** [comment]
I can't reproduce this after trying 5 or 6 times. I'm using unstable with an episode file. I hit the right arrow till the remaining time was < 30seconds and hit both OK and play. Both buttons made the video start, OSD hide, and the Next Episode button show up with focus.

**Comment by michaelcresswell** [comment]
I think I can reproduce this with [Jellyfin-Roku-dev-e403b2ce331c359d53f6bd6a012c8bfe97833421](https://github.com/jellyfin/jellyfin-roku/suites/18318353770/artifacts/1059780270)

1) Use the right arrow key to fast forward to within 30 seconds of the end of an episode
2) Seek Bar display hides and Next Episode button appears but is out of focus (grey instead of white)
3) Pressing Ok or any arrow keys in an attempt to access the Next Episode button brings up the OSD
4) Backing out of OSD or allowing it to timeout leads to the Next Episode appearing in focus and it can be pressed

Tested with several direct play episode and seen with all of them.

**Comment by 1hitsong** [comment]
Here's a video of me following the steps above on Unstable branch. I can't recreate.

https://github.com/jellyfin/jellyfin-roku/assets/3330318/d188714d-0ef4-47c4-9596-f588d69f19bd
