### ISSUE TITLE
Forced subtitles does not activate

### ISSUE THREAD

**Issue by Alliyance** [jellyfin-archive/jellyfin-roku-legacy#1571]
## Software Versions

- Jellyfin Server Version:  10.8.13
- Roku Client Version:  2.0.0

## Describe the bug
Any movie who has Forced subtitles, doesn't turn on anymore. You need to manually turn it on.

## How To Reproduce

1. Play a movie who has Forced subtitles
2. Check subtitles menu with down arrow
3. In CC, you'll see it's mark None

## Expected behavior
Should turn on by itself

## Connection Information

- Is server local or remote?
- Is server connection HTTP or HTTPS?

**Comment by 1hitsong** [comment]
Thanks for the bug report. We're looking into the subtitles issues.

FYI for anyone experiencing this issue: We can't update the app till January 2nd due to the [roku holiday blackout](https://blog.roku.com/developer/channel-store-blackouts-2023). **_If_** we're able to fix it before then and push an update release on the 2nd, the app would hit Roku devices a few days later.

Unfortunately, the only workaround until then is to sideload v1.6.6. 

You can find the app here: https://github.com/jellyfin/jellyfin-roku/releases/tag/v1.6.6

You can find instructions here: https://github.com/jellyfin/jellyfin-roku/discussions/897

**Comment by Alliyance** [comment]
Also I used srt subtitles and after 5 min into a movie, they disappear.
