### ISSUE TITLE
Resumeable state not set until movie detail view refresh

### ISSUE THREAD

**Issue by 1hitsong** [jellyfin-archive/jellyfin-roku-legacy#1647]
## Software Versions

- Jellyfin Server Version:  Latest
- Roku Client Version:  Latest

## Describe the bug
If you watch a movie past the resumable point, the resumable state isn't reflected on the movie detail view unless you refresh the view.

## How To Reproduce

1. Go to a movie detail view
2. Play movie past the resumable point
3. Press back to return to movie detail view
4. The view does not show the percentage played bar. Also, if you press play button it will start the movie from the beginning.

## Expected behavior
I expected the percentage played bar to show and if I clicked play the Playback Options popup would appear.

**Comment by cewert** [comment]
Possibly a duplicate of #1624. At the very least they are related.

**Comment by dathbe** [comment]
I assume this is the same issue, but it also happens when you already have a resume point in a video:

1) Choose to resume video that has a save point
2) Press "Play"
3) Select "Resume playing from 43:30"
4) Play video for a while
5) Press back to return to movie detail view
6) Press play
7) It will STILL say "Resume playing from 43:30"

I agree this seems to be a refresh issue because if you press back one more time from the movie detail view to get to the home screen, and then go back into the movie detail, it will allow you to "resume playing at" the new save point.  Seems like a quick refresh of the movie detail page when a movie is stopped would solve this.

**Comment by 1hitsong** [comment]
@dathbe Yep. Same thing. It's because the resume point is established on the detail view (whether it be 0 or 43:30) and isn't updated when you go "back" to the view from the video player. It's only being refreshed when going "forward" to it from another view.

**Comment by cewert** [comment]
Fixed by #1771
