### ISSUE TITLE
Separate Brightscript from XML Files

### ISSUE THREAD

**Issue by mcrowson** [jellyfin-archive/jellyfin-roku-legacy#20]
The brightscript should probably not live inside XML files. Not sure the appropriate file structure and architecture, still combing the developer docs, but BS in XML seems off.

**Comment by bisby** [comment]
BrightScript in XML files in the Roku examples seems reserved for small init bits and minor rendering control. Some of mine started that way and then got stretched beyond the original intent.

At some point I decided I wanted to build up `ContentNode`s as the main data model and go more Object Oriented, but half backed out of that once I realized how gross it looks to call `ContentNode.callFunc("interface_function")` (I do like the Object Oriented style for holding the data, but really don't like it for manipulating the data). But I didn't fully commit either way, since I didn't really foresee anyone else looking at the code.

**Comment by mcrowson** [comment]
Yea I've seen it in their examples, I was just trying to wrap my head around how to write tests for it and falling short. Is it possible to move that code into its own brightscript alongside the XML?

**Comment by bisby** [comment]
Yep. I already do that in a few places as well. For example, for TV show components, there are `group-description.xml` and `group-description.brs` and then instead of using `<![CDATA[` inside of a wrapped script, it is merely `<script type="text/brightscript" uri="pkg:/components/tvshows/group-description.brs" />`

I wasn't sure how worth it it was to have a separate `.brs` for every XML file (as most XML files have at least an `init` function in them). I personally like the idea but then I start to second guess myself. If you think this is the right path, I'm on board.

**Comment by mcrowson** [comment]
Let's separate them, i don't mind having separate files for them.
