### ISSUE TITLE
Dolby Audio above 5.1 is Downmixed

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin-archive/jellyfin-roku-legacy#229]
**Describe the bug**
Any Dolby/non-DTS audio above 5.1 channels is automatically down mixed to Stereo. This _could_ be a Roku limitation.

**To Reproduce**

1. Play content with Dolby 5.1 audio, observe that Dolby Digital appears on home theatre receiver. TV reports that it is receiving Dolby Audio over HDMI.
2. Play content with DTS 5.1 or 7.1 audio, observe that DTS appears on home theatre receiver. TV reports Bitstream audio over HDMI.
3. Play content with Dolby 7.1 (TrueHD or Atmos), observe that Stereo appears on home theatre receiver. TV reports that it is receiving Stereo audio.

**Expected behavior**
The correct audio format plays through with no issues.

**Additional context**
My setup is rather unique. The TV natively supports Dolby Audio and bitstream to passthrough over HDMI. My speaker system only has Analog, TOSLINK, and Coaxial inputs, so it can accept bitstream audio up to 5.1 max (and most modern codecs fallback to this).

To play back media, devices are connected to the TV with HDMI, and then the TOSLINK output of the TV is used to connect to the speakers. Though the TV does not decode DTS, it will still pass it through, so the test is valid.

**Comment by neilsb** [comment]
Roku should [support 7.1 audio](https://developer.roku.com/en-gb/docs/specs/streaming.md#supported-audio-codecs) so it's more likely something we're doing.  

The new [deviceCapabilities.brs](https://github.com/jellyfin/jellyfin-roku/blob/93c64f7422232ab9f035f0015a0bcfb15bce1041/source/utils/deviceCapabilities.brs) file which was just merged in as part of LiveTV now lets us tell the server what the Roku supports, so we can start to transcode less, but I think we still have a fair way to go to get this file _perfect_ due to a lack of understanding of a few things at present.

When requesting the Audio Source, we use an in-built [Roku query](https://developer.roku.com/en-gb/docs/references/brightscript/interfaces/ifdeviceinfo.md#getaudiooutputchannel-as-string) to determine if a 5.1 Surround output is connected and if not, when transcoding we request 2 channel.  We'll need to see what is reported when a 7.1 output is connected and improve the code that decides what we ask the server for.  As @cewert mentioned elsewhere, the Roku itself can tell us the "closest" supported match of Audio data which is something we can probably make use of.

**Comment by anthonylavado** [comment]
I saw there are Roku settings for what audio formats to send out, so I'll play around with those too.
