### ISSUE TITLE
Can't click OK on error messages

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin-archive/jellyfin-roku-legacy#237]
There is a small bug in the interface. Any time you get an error message and you go to click on "OK" it does nothing. You end up having to hit back arrow to get out of the error message. I get it most often when it won't load a Live TV channel that I was just kicked out of, or when Live TV on Jellyfin is being weird and won't load any Live TV channels.

**Comment by neilsb** [comment]
I've been unable to replicate this issue.   Is it all error message popups that you see this behaviour, and is it every time?

**Comment by Protektor-Desura** [comment]
The only time I see this error is in Live TV and yes every time the error message pops up I can't just click "OK" I have to click on the back arrow on the remote to get out of the error message.
The easiest way to duplicate this error is if you are using xTeVe and you just shut down xTeVe so it can't stream channels which is like not being able to connect to the streaming server. Then you will get an error that you can't OK out of.

**Comment by neilsb** [comment]
OK - think I've tracked this down.  Only seems to happen on the "Error loading Channel Data" dialog.  The other LiveTV Related one (Error During Playback) does not seem to suffer from this.

Looks like its to do with not handling the button presses, which is not as trivial as it may seem since this dialog is created in the Event Loop, rather than in a scene.  May need a little refactoring to resolve it.
