### ISSUE TITLE
Playing videos without audio crashes to the main menu

### ISSUE THREAD

**Issue by timandrews335** [jellyfin-archive/jellyfin-roku-legacy#243]
**Describe the bug**
I've got four files encoded with H.264 that were generated from PowerPoint slides.  Two of them have audio, and two do not.  Playing the files without audio causes the Roku client to crash to the main menu, whereas it works in the web interface.

**To Reproduce**
1. Add files mp4 files without audio to a library
2. Play them in the Roku player
3. Note the crash to the main Roku menu

**Expected behavior**
Files should play on the Roku player

**Logs**
No logs were recorded for the crashes.

**Screenshots**

**Additional context**

**Comment by neilsb** [comment]
This is due to us (incorrectly) assuming that 1st Media Stream for an item is Video, and the 2nd is Audio.  This was a quick way to get things working, but for numerous reasons (this, #188, #231 and possibly others) this needs properly implemented.

There is likely a quick check we can do for when a video has no audio, that would resolve this specific problem.
