### ISSUE TITLE
Thumbnails for seek slider are wrong or missing in roku app

### ISSUE THREAD

**Issue by walterwatson** [jellyfin-archive/jellyfin-roku-legacy#349]
First Thank you for your efforts and hard work on jellyfin.

**Describe the bug**
When seeking forward/back the thumbnail is not always present.  But if it is present it's not correct to the position the slider is in.

**To Reproduce**

Play a video, press roku remote left / right button and observe the thumbnail behavior on screen nearest the seek slider.

**Expected behavior**
To have thumbnails that are somewhat close in time to the current position of the seek slider shown on the TV

**Logs**
I don't see any errors.

**Additional context**
This feature works in the roku version of emby but not here in jellyfin.

**Comment by neilsb** [comment]
Thumbnail seek support is something that is planned, hopefully when the whole overlay screen (or trickplay as Roku call it) is re-vamped.  There are also additional discussions on the server side about efficient generation of thumbnails going on too.

Just for the sake of clarity I've changed this to a enhancement rather than a bug, as this has never been present in the Jelly Roku Client.  The Jellyfin Roku client has been written from scratch and has never used any of the code Emby Roku version, which is not Open Source.

**Comment by walterwatson** [comment]
Thank you for taking the time to respond to my question (and for your efforts on jellyfin).  I'm glad to hear that this is a enhancement to come!  Sorry I had assumed that the emby code was forked as well.  For the short time I had used emby I recall there being 'bif' files generated from ffmpeg; and we were given option to have them located near the source media or in the server cache dir as a configurable option in the server settings.  Anyway, that's awesome!  Cannot wait.  Have a great day, stay safe.

**Comment by jimdogx** [comment]
I believe this is fixed by #753 

Closing issue.
