### ISSUE TITLE
Audio track selection is not respected during playback

### ISSUE THREAD

**Issue by DanielVukelich** [jellyfin-archive/jellyfin-roku-legacy#351]
**Describe the bug**
I have an .mkv file with two audio tracks, English (default) and Japanese.  When I select the Japanese track in the video file's menu (Audio->Jpn Dolby Digital 5.1) and then play the movie, I still get the English audio track.  This behavior is not present in the Jellyfin web client when playing this file with the Japanese track selected.

The audio track that the player uses is not always the default track.  In my reproduction steps below, my player always selects the non-default developer commentary track.  Again, on the web client, I can select either track and it works fine.

**To Reproduce**

1. Add https://github.com/Matroska-Org/matroska-test-files/blob/master/test_files/test5.mkv to one of your playback libraries
2. Select that file from the jellyfin roku app
3. Move the cursor over the the "Audio" tab and click it
4. Verify that the default track "AAC Stereo Default" is selected
5. Press "back" button
6. Play the movie
7. Listen to hear which audio track is played
8. Go back to the file's menu and back to the "Audio" tab
9. Select "Eng AAC Mono (Commentary)"
10. Play the file again
11. Listen to hear which audio track is played

**Expected behavior**

The first time I play the file (when default track is selected), I would expect to hear one of the characters talk about the colossus of rhodes.  Instead, I hear one of the movie's animators discussing the current scene.  The second time I play the file (after selecting commentary track), I hear the animator's commentary, as expected.

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ParasiteDelta** [comment]
I have a similar issue. 

While multitrack audio selection is currently not supported for shows on certain devices, such as Roku units, I do have scripts set up to remux my collections for primary audio switching. I remuxed a season of anime that I'm currently watching to switch the primary audio and subtitle tracks from _English to Japanese,_ and from _Assistive to Full Captions,_ respectively. After the change, literally every single client that I've tested the remuxed season on reads and runs it properly; Japanese audio as default, full captions as default, on Jellyfin Android, Desktop, and multiple media players. However, _**every Roku unit that I've tested, and even an Android TV unit, does not respect the newly-set defaults; English is still the default audio track, Assistive is the default subtitle track.**_ 

Not only is the ability to select tracks a relatively standard function, but not even remuxing appears to work correctly with specific clients. Remuxing the season to force specific tracks would just lock out alternate audio, and removing the tracks altogether is anything but a solution. When you take into account that most people who will be using this software have vast libraries of varying types of content, being able to select your desired tracks is an absolute necessity, unless we get some kind of weird transcoding option to specify preferred tracks on the fly, which would still take too much time and be subject to an entire article's worth of frustrations.

If audio track selection for movies isn't working, and the software is not respecting defaults, then something else is going on.

**Problem: Jellyfin not respecting remuxed defaults/selected audio (movies)**
**To Reproduce: **
1--Remux a dual-audio/dual-source movie or series
2--Attempt to play on a restricted platform (Roku, Android TV)
**Expected: plays selected/specified default track**

**Comment by neilsb** [comment]
Two problem here (at least).  

Firstly, when direct playing we are not correctly telling the Roku device which track to use.  We are telling the server, which (when transcoding) should result in the correct track being used, but when direct playing we neglect to tell Roku which track to use.  As a result Roku chooses the "best" track itself, based on the preferred language set the user in the OS.   In the linked mkv file, since the main track does not have a language set, but the Audio Commentary has language set to English, Roku will choose this by default (for users with English set as their preferred language).

Second problem is that investigation of this bug has identified a problem in the server (jellyfin/jellyfin#5279) where the list of tracks in the file does not match what the server reports.  This can cause problems with the displayed subtitle and track audio track played.

In the meantime, as a workaround, you can set the Audio Track used directly within Roku by pressing the * button during playback and setting the Audio Track and Caption Track from the Roku OS menu.
