### ISSUE TITLE
Saved server list

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-roku-legacy#354]
It would be very useful to have a list of bookmarks for multiple servers with saved URLs and credentials. Currently, the user has to enter the url and login everytime they switch servers.

**Comment by jimdogx** [comment]
I'm currently working on this.  I have a local version that saves previous connections.  But only the URL, not the username or password.

Still debating if it's a good idea to save the password.  I might only save the username.  Having to type in just the password is still way better than: URL, Username and Password 😄

**Comment by neilsb** [comment]
It shouldn't be necessary to save the password, and in fact that's a change that we are needing to make to the current way we manage logins.

Once logged in, we receive a token from the server which is what is used for authenticating any requests made after this point.  If we store that with the user instead of the password then that would be the better option.  Currently the token is non-expiring, but can be revoked from the server if required, which would require a user to log on again.

**Comment by TwitchBronBron** [comment]
If we don't get to saving the token right away, I'd definitely prefer letting the user decide if the password will be saved or not. I definitely don't want to re-enter the password every time for the Jellyfin servers I use.

**Comment by jimdogx** [comment]
PR created.  I looked in to using a token, but other than the "api" token, the only other thing I saw was a "quick connect" feature that I don't have enabled on my servers and don't know much about.

Since the client already saves the password, I went with that.  If / when user logins are refactored to use tokens instead, this new code is easily updatable as well (literally change "password" to "token" in a few lines).

I tested this with two servers.  One remote and one local.  It all appears to work on my end (really nice to be able to simply click and change servers with no typing!!!).  Would be great if someone else could test this as well.
