### ISSUE TITLE
Channel Support

### ISSUE THREAD

**Issue by crobibero** [jellyfin-archive/jellyfin-roku-legacy#384]
**Is your feature request related to a problem? Please describe.**

Would love to get proper "Channel" support working

**Additional context**

> I just did a fresh install of jellyfin 10.7 (windows version if that matters) and added the lazyman plugin. Followed the setup and got it working it chrome, but for some reason when I login on my roku I can click lazyman but it immediately jumps to the screen where you choose what resolution you want. I've tried uninstall the roku app and reinstalling but it always skips the choice for NHL or MLB as well as the date for the games. I cant go back a page or anything, and when I try to play something the app crashes and takes me back to the roku homescreen.

Reference issue: https://github.com/crobibero/Jellyfin.Channels.LazyMan/issues/12

In this example, opening the channel should go:
```
Sport -> Date -> Game -> Quality -> Play
```

**Comment by neilsb** [comment]
So a few interesting things here that actually affect some of fundamental ways the Roku app was developed

1. The "Sport", "Date" items you'd expect to see are not showing due to the "ChannelFolder" data type not being handled by the app.  That's an easy enough thing to fix
2. The resolutions are showing as they are Channel data types, and the roku app knows how to show them.  They are showing immediately as when we request the item list, by default we have the list to be recursive.  I think we should switch the default to non-recursive.  Certainly needs to be non-recursive right here
3. When we do go to try and play the channel, the MediaStreams array is empty.  Currently we only look at the MediaStreams array rather than using the Media Sources Array.  As a net result of this we (incorrectly) look at each stream and try to determine if we need to transcode it ourselves, and if we do we proceed to build a transcode URL ourselves - rather than using the PlayBackInfo endpoint to let the server determine if transcoding is required based on the DeviceProfile, and building the Transcode URL for us 

So - there are a few things to fix for this, that should improve the overall Roku experience.
