### ISSUE TITLE
Media grouped into collections do not list in the proper order. 

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-roku-legacy#391]
Movies in a box set only display in alphabetical order by title.  This makes it hard to watch a series if the titles don't give you a clue or you don't know the proper order.  Please change the default sort to release date.

**Comment by neilsb** [comment]
I'm not sure "Release Date" should be the default sort order.  I don't think this is the case on other clients.

Currently there are no sort/filter options enabled for BoxSets (Collections), but there are easy enough to add in.  This would allow users to switch the sort order to Release Date if required, but since collections can contain any sets of movies, TV Series, etc etc I don't think Release Date will always be the most logical sort order.

Could potentially look at adding a default sort order when we get Roku User Preferences implemented, but that would likely have to affect all Collections, whatever the content.

**Comment by CDrummond** [comment]
I'm also experiencing this issue. I have added some movies to a collection using the Jellyfin webUI. With the web UI I can sort by release date, but not with the Roku app. My collections only have 'Name' as the sort option, nothing else. Is this correct? I would have though with #393 there should be more sorting options?

I have tried 1.4 build 8 installed from the Roku store. But, I also checked out this repo, built, and installed the dev version - no change.

(Sorry - I realise this reads more like a support request. I would have posted on the support forums, but these are closed.)

**Comment by countbuggula** [comment]
> I'm not sure "Release Date" should be the default sort order. I don't think this is the case on other clients.
> 
> Currently there are no sort/filter options enabled for BoxSets (Collections), but there are easy enough to add in. This would allow users to switch the sort order to Release Date if required, but since collections can contain any sets of movies, TV Series, etc etc I don't think Release Date will always be the most logical sort order.
> 
> Could potentially look at adding a default sort order when we get Roku User Preferences implemented, but that would likely have to affect all Collections, whatever the content.

"Release Date" actually is the default sort order for both the web and android client.  Either way, release date makes way more sense than alphabetical in 99% of actual use cases.
