### ISSUE TITLE
Library Thumbnails on Main Screne

### ISSUE THREAD

**Issue by mcrowson** [jellyfin-archive/jellyfin-roku-legacy#4]
The libraries on My Media should have thumbnails similar to the webapp
![image](https://user-images.githubusercontent.com/6452882/56855975-1a709800-691f-11e9-869b-f95e70d6f396.png)

**Comment by bisby** [comment]
![image](https://user-images.githubusercontent.com/619700/56857676-3df30d00-6936-11e9-80df-a704c500f073.png)

There are multiple main menu options. Ive built `My Media (small)` for now as it took the least amount of dev work to get the most functionality.

I'll be finding if "what shows up on the home screen" is stored in cookies in the webapp, or if it's stored on the server and can be copied down to the Roku.

**Comment by cghouly** [comment]
Looks like this is the call the webapp makes to pull the image:
`/emby/Items/{Id}/Images/{Type}/{Index}/{Tag}/{Format}/{MaxWidth}/{MaxHeight}/{PercentPlayed}/{UnplayedCount}`

**Comment by cghouly** [comment]
Also would implementing this feature require creating an Options menu for `My Media` or `My Media (small)` so the end user can choose between thumbnail or text?

**Comment by bisby** [comment]
Yep. This would require a user setting, which we don't really have a great place for in depth user settings at the moment so I just picked a default.

Also, since it's purely a cosmetic webapp-parity thing, it seemed low priority to "fix".

We should also be considering here how much we want to make the Roku app look like the WebApp (ie, what we're doing now), vs how much we want to make it look like a native Roku app (ie, redo some of the interactions/UI to make it look more like existing apps).

If we go WebApp, and this is already something that the API would have in user config, I would also be ok with asserting that for now, user settings should be changed in the WebApp and we interact with the config in a read only capacity.

If we want to change things up and make it look much nicer, we might not bother worrying.

slight tangent: it would also be super great to get some designer input. I was originally only following the webapp design because I have 0 design skills. If someone else has a vision for how things should look, I'd be 100% on board.

**Comment by cewert** [comment]
This was added in #83
