### ISSUE TITLE
Plays reported twice, visible on trakt

### ISSUE THREAD

**Issue by SenorSmartyPants** [jellyfin-archive/jellyfin-roku-legacy#431]
**Describe the bug**
Two playbacks recorded when only viewed once.
JF 10.7.2, Current Roku 1.4.9?

**To Reproduce**

1. Have trakt plugin installed. 
2. Play a video to finish on Roku client. 
3. View trakt history, two playbacks in history one, with current time (looks like from scrobble) and one 5 hours earlier (== time zone offset from UTC, looks like a marked as watched).
 I can tell scrobble/checkin vs marked as watched when viewing this history using SeriesGuide (different icons)

**Expected behavior**

Only one playback should be recorded.
My guess is that the roku client is sending a set watched API call to JF after the playback sends, which is unnecessary.

**Screenshots**

![image](https://user-images.githubusercontent.com/991618/116448750-12ee6d00-a81f-11eb-8074-68b822f6428a.png)

**Comment by neilsb** [comment]
Yup, confirmed this and that removing the call to Set Watched call on completion of video results in it only appearing once.

Additionally, it looks like we should be sending UTC timestamps to the server when marking things as watched, rather than local, which accounts for the incorrect time you saw.  Will get that resolved too.

**Comment by anthonylavado** [comment]
By the way, this is in the beta channel as of Saturday May 1st, and the main channel should get released by Roku on Tuesday. Version 1.4, build 8.

**Comment by SenorSmartyPants** [comment]
Seems to fix this for us. Thanks.
