### ISSUE TITLE
7.1 Vorbis Audio is Silent, But 5.1 Works just fine

### ISSUE THREAD

**Issue by michaelharmonart** [jellyfin-archive/jellyfin-roku-legacy#463]
**Describe the bug**

When playing a video with 7.1 vorbis audio, there is no sound, but when playing 5.1 audio in the same vorbis format, audio works fine. I have audio transcoding turned off, so all downmixing to the 2 channel stereo system I have is being done in the jellyfin app or somehwere farther down along the chain. This could be an issue somewhere other than the jellyfin app but I thought I'd make a bug report just to be sure

**To Reproduce**

1. Play a video with 7.1 vorbis audio, it's silent
2. Play a video with 5.1 vorbis audio, it works fine and downmixes to stereo properly.

**Expected behavior**

I would expect both 5.1 and 7.1 surround sound to work, since clearly the client can downmix 5.1 audio.

**Logs**

I don't have any logs but let me know if you need something.

**Comment by neilsb** [comment]
Standard Roku apps themselves cannot perform any transcoding or downmixing.  The CPUs in the units are not particularly powerful, and the OS doesn't provide a way to do this.  Basically the app is responsible for allowing the user to choose the URL for the stream, and then passes that off to the RokuOS to actually play.   Any downmixing that is being performed will be done by the RokuOS itself.

I think in order to for these to play a 7.1 source properly, you'd either require to enable transcoding or have an external decoder that can accept 7.1 audio.

**Comment by michaelharmonart** [comment]
Alright thank you. Looks like my projector is probably doing the downmixing then, since I don't have any receiver between the roku and it. Looks like it isn't the jellyfin app's fault.
