### ISSUE TITLE
Videos with Opus audio not playing sound with VP9/WebM and MKV/AV1

### ISSUE THREAD

**Issue by Hooloovoo** [jellyfin-archive/jellyfin-roku-legacy#483]
**Describe the bug**
I have a number of video clips in combinations of containers and codecs on Jellyfin. I am using a Roku Streaming Stick+ (3810 EU) running Roku Jellyfin version 1.4 build 8. Most files play back as you would expect, but two combinations of container/video codec/audio codec play back without any sound.

Specifically:
- MKV container H264 video Opus audio works fine
- mp4 container H264 video AAC audio works fine
- MKV container VP9 video AAC audio works fine
- MKV container H264 video Opus audio works fine

But
- webm container VP9 video Opus audio codec plays back with no sound
- MKV container AV1 video codec Opus audio codec plays back with no sound

**To Reproduce**
1. Find a video file that is either webm/VP9/Opus or MKV/AV1/Opus
2. Play it back on Roku Jellyfin
3. Video will have no sound

**Expected behavior**
Video would have sound, as it does on the web player, Kodi or mobile clients.

**Logs**
[20210902_Roku_Jellyfin.log](https://github.com/jellyfin/jellyfin-roku/files/7101621/20210902_Roku_Jellyfin.log)
This is the relevant part of the Jellyfin server log as I play each of the files that have no audio playing. Please let me know if the transcoding logs for any of these would also help.

**Additional context**
I have seen Issue #464, but it does not sound the same because it plays, just without sound
I have seen Issue  #417, which sounds similar, but that issue was closed.

Do any of the main contributors already have access to a 3810 Streaming Stick+ or do they still need this?

**Comment by neilsb** [comment]
I think #417 does solve your problem.  I have a 3810 that is my primary dev stick and VP9/Opus certainly works on that.   However, I think the issue is that #417 is currently only in our Beta release, and not yet on the store version.

Would you be able to install the beta version and test the files with that?  The link to install it is in the README file at the root of this repository.   It can be installed alongside the Store version, so shouldn't affect the main app in any way.  (Just a note - on the current beta version, h265 media may not play correctly)

I'll talk to team about getting an updated Beta version out, and then that pushed to the store ASAP, as I'm aware there hasn't been a store release in a while.

**Comment by Hooloovoo** [comment]
Ah yes, sorry -- I thought I had checked the Beta was the same version I was running, but I have tested the Beta and it is working fine. Sorry for the noise and thank you for your great work. If you already have a 3810 then I will not offer to buy you one, then :).
