### ISSUE TITLE
Strange issue with John Wick 2

### ISSUE THREAD

**Issue by tydog98** [jellyfin-archive/jellyfin-roku-legacy#576]
**Describe the bug**
At 3:30 there is a scene in the movie where a guy speaks Russian and a subtitle pops up. This specific moment crashes the video playback for me and sends me back to the video select screen. Setting the subtitles to English instead of off fixes this crash, but there are no actual subtitles displayed. This issue does not happen with Jellyfin Media Player

**To Reproduce**
Watch John Wick 2

**Expected behavior**
Should not crash

**Comment by neilsb** [comment]
I wonder if this is due to a forced subtitle stream.  When you're playing the movie and press down (to get the subtitle select popup), what subtitle tracks are shown?

Are you able to run `ffprobe` against the media file and share the results?

**Comment by jimdogx** [comment]
I wasn't able to get the movie to crash at 3:30 or 12:30 (both places with forced subtitles).  However, I do get a crash if I select the last subtitle listed (in my case Danish):

![Screen Shot 2022-04-25 at 6 04 45 AM](https://user-images.githubusercontent.com/18198517/165085724-ed796591-ad80-422a-b611-19b5c81a4382.png)

The array is 0 - 7, but TextIndex = 8.  Not sure if this is related.

**Edit:**

Turns out there really are 9 items, so I'm not sure why the array is only 0 - 7.  Here are screen shots from the web player and from a debug statement I added to the Roku client:

Web:
![Screen Shot 2022-04-25 at 6 09 43 AM](https://user-images.githubusercontent.com/18198517/165086751-937a584f-612d-486d-a247-e82d0977c8b0.png)

Roku:
![Screen Shot 2022-04-25 at 6 12 19 AM](https://user-images.githubusercontent.com/18198517/165086772-e844b58e-84cc-44ee-97e3-79b70f52ca72.png)

**_The code appears to assume that the array Video.Subtitles is the same as Video.availableSubtitleTracks_** which maybe is an issue (perhaps separate from this one)

**Comment by tydog98** [comment]
> 

It shows the two English subtitles and two Spanish subtitles. [Here is what I got from ffprobe](https://pastebin.com/Mge9Xy4L)

**Comment by jmegaffin** [comment]
I'm experiencing a similar problem.  I'm trying to play a video with two audio streams (English, Japanese) and one subtitle stream (English).  By default, the video plays with English audio and no subtitles (despite my preferences, which is another issue entirely).  Whenever a subtitle would pop up if they were enabled, it crashes and jumps to the next episode.  If I enable the subtitles, the video doesn't crash, although they do actually show up, unlike in @tydog98's situation.  [The file seems okay, according to `ffprobe`.](https://gist.github.com/jmegaffin/c95ccc94ca0fc467f844a81b8278bd1a)  I tried different burn-in settings, but it makes no difference.  The server logs also don't say anything useful, just `Playback stopped reported by app "Jellyfin Roku" "1.4.12"`.

**Comment by tydog98** [comment]
Just tried John Wick 3. Crashes at the first bit of dialogue again unless I turn on English subtitles. Still doesn't actually show them though.

**Comment by 1hitsong** [comment]
If you're still experiencing this issue using the latest Roku client release, please post to the troubleshooting forum. There are tons of great people help who can help dive into issues like this.

https://forum.jellyfin.org/f-troubleshooting
