### ISSUE TITLE
24-hour clock shows 24:xx rather than 00:xx after midnight

### ISSUE THREAD

**Issue by tremby** [jellyfin-archive/jellyfin-roku-legacy#609]
**Describe the bug**
Subject says it all.

**To Reproduce**

1. Set clock to 24-hour
2. Wait until it's after midnight

**Expected behavior**

00:00

**Logs**

**Screenshots**

![PXL_20220526_074527275](https://user-images.githubusercontent.com/199635/170442957-d5578e4d-5770-40c9-a31d-849fe63f5a8d.jpg)

**Additional context**

**Comment by cewert** [comment]
> Subject says it all.

Was the time accurate despite showing 24 instead of 00? What were you doing before you noticed? Watching a video? Just come back from the screensaver? Since you didn't specify does that mean you were running the latest version of stable and not dev?

Please provide as much information as possible when reporting bugs.

**Comment by tremby** [comment]
> Was the time accurate despite showing 24 instead of 00?

Yes. The time is accurate.

> What were you doing before you noticed? Watching a video?

Yes, I think so. I have seen this more than once, by the way. I'm not sure if it's ever been in idle or screensaver state while flipping from 23:59 to 24:00 or if it must be in a video. If I think of it just before midnight, I'll try to find out.

> Since you didn't specify does that mean you were running the latest version of stable and not dev?

Yes.

> Please provide as much information as possible when reporting bugs.

Yeah, fair enough; apologies. I felt like this one was probably a cut & dry mistake in the source code and so I was scant with details.

Now that I look at the code in question, I see there's nothing obvious. [The `ifDateTime` interface's `getHours` method](https://developer.roku.com/en-ca/docs/references/brightscript/interfaces/ifdatetime.md#gethours-as-integer) says it returns 0 to 23, and [the relevant jellyfin-roku source](https://github.com/jellyfin/jellyfin-roku/blob/master/source/utils/misc.brs#L44L69) uses that as is and hasn't changed in years.

Looks like an upstream bug to me, but it could probably be protected against nonetheless with `hours = time.getHours() MOD 24`.

**Comment by cewert** [comment]
Yea we have a custom overhang and clock but like you said I don't think it's been changed recently. Do you remember how long ago you first noticed this?

The only thing I can think of is maybe the scenemanager passthrough below is not working but that only gets called after backing out of a video or screensaver I believe. I'll probably need to do some testing. https://github.com/jellyfin/jellyfin-roku/blob/26d9360fd3982e4395da2c4aef32b2399b4a81e6/components/data/SceneManager.brs#L211-L214

**Comment by tremby** [comment]
> Yea we have a custom overhang and clock but like you said I don't think it's been changed recently.

Looked from the code I was looking at like it hadn't been changed in at least 2 years.

> Do you remember how long ago you first noticed this?

Couple of weeks? But I've only had my Roku a couple of weeks. I don't think there have been any releases since I first got it and installed.

**Comment by neilsb** [comment]
> The only thing I can think of is maybe the scenemanager passthrough below is not working but that only gets called after backing out of a video or screensaver I believe. I'll probably need to do some testing.

If you are going to look at it, #591 is maybe worth having a look at (in case you hadn't seen it).  Is a first step at make updating screen content easier, especially when backing out of things.

**Comment by cewert** [comment]
@neilsb So I put a breakpoint in the overhang function `resetTime()` to see if it's being called as it should be. This function should be called anytime our custom clock reappears on the screen (so that our custom clock can be re-synced with the roku device's time). I've confirmed it's being called correctly after exiting the screensaver. But when hitting back to exit a video, this function never gets called. Which resulted in the clock being out of sync (1 minute slow in my case).

https://github.com/jellyfin/jellyfin-roku/blob/886566bdae98f1deea5352bbea42d5b47c2e9a13/components/JFOverhang.brs#L65

~~Not sure where to look now with all the new scenemanager and JFScreen stuff. Thought I'd run this by you before I dig any deeper.~~

I need more coffee. Going to start with the scenemanager passthrough i linked above

**Comment by tremby** [comment]
I see the bug again right now. I'm not sure what state it was in at the stroke of midnight. Either on one of the menus or watching a show. I watched the menu screen for a while now and saw it tick up from 24:15 to 24:16.

I tried starting another show and then exiting with the back button. The clock still showed 24:something.

I then brought up the search screen via * then search. The clock then changed to 00:something.

**Comment by tremby** [comment]
Still seeing this. I'm not sure what version I'm on right now. Just saw it tick up from 25:04 minute by minute to 25:07 😆

**Comment by tremby** [comment]
I just saw it go from 23:59 to 24:00 while video was not playing, on the jellyfin home screen. I think I had not pressed a button since a video ended.

**Comment by neilsb** [comment]
Looks like this is actually due to a peculiar way we manage the time in the overhang

```
sub updateTime()
    if (m.currentMinutes + 1) > 59
        m.currentHours = m.currentHours + 1
        m.currentMinutes = 0
    else
        m.currentMinutes = m.currentMinutes + 1
    end if

    updateTimeDisplay()
end sub
```

Suspect this was done to avoid creating a new `roDateTime()` every time we update the time, but that could be done in other efficient ways that wouldn't have this problem.

We could also do with standardising on the single helper functions we use for formatting time which have now been added to `misc.brs`
