### ISSUE TITLE
Drop built in support for 720p and have Roku autoscale

### ISSUE THREAD

**Issue by cewert** [jellyfin-archive/jellyfin-roku-legacy#70]
In the manifest file we have `ui_resolutions=hd,fhd` which is telling Roku we have two versions of the GUI, one for 1080p and and one for anything above 720p. Is this intentional? Is the app currently designed with this in mind?

When viewing the app on my 1080p screen (with 1080p selected in Roku settings) I noticed the GUI for the app doesn't look right (spacing off, missing buttons etc.). I then set up RALE and noticed that the app is forcing my resolution to 720p somehow?

I changed the manifest file to `ui_resolutions=fhd` , deployed, and now the app looks much better. I can actually see the little button for search on the main page, TV and Movie detail screens look better and I can see all the buttons!

I suggest we design for 1080p (fhd) and let Roku automatically scale the app down as needed like [Roku recommends](https://developer.roku.com/docs/developer-program/core-concepts/specifying-display-resolution.md)  (see Recommended intended resolution and Autoscaling guidelines)

**Comment by bisby** [comment]
Nope. this was a complete misunderstanding of the manifest file. I thought we needed to specify which resolutions the app COULD run at, rather than what resolutions it was built for.

Autoscaling would be great, and would fix a ton of other issues, and also we could strip out a TON of poorly written code that was trying to be clever about scaling, thinking we were going to need to go percentage based ("bar is the left 10% of the screen", etc)

**Comment by cewert** [comment]
I was wondering what all the math was for hah I was too scared to touch the layout. Still trying to wrap my head around Brightscript

I'll change it real quick and send a PR
