### ISSUE TITLE
---

### ISSUE THREAD

**Issue by halictuz** [jellyfin-archive/jellyfin-roku-legacy#734]
---

**Comment by Sector14** [comment]
I'm using 10.8.1 with a Roku Express 4k+ and it's playing back a BluRay disk via direct play (1080p, h264). Just deployed 10.8.3 to test against that and it also direct plays for me.

My issue is direct really seems to stutter :(

**Comment by lakerssuperman** [comment]
> **Describe the bug**
> 
> Direct Play not working anymore, it worked before Jellyfin 10.8.x though. Same for android/firetv stick, same issue there.
> 
> **To Reproduce** Use ROKU with latest server version of jellyfin (mp4, mkv, h264, h265, AC3, DTS etc. nothing works anymore without transcoding it. which wasn't the case before the latest version. Same issue for android/firetv stick too, but that has kinda a workaround by using an external player like VLC, because Exoplayer and libvlc just doesn't play anything anymore without transcoding. Some files with xvid/divx run, but no sound etc. Which is weird because EVERYTHING ran perfectly fine before Jellyfin updated to 10.8.x since then Direct Play is pretty much completly broken.
> 
> **Expected behavior** Video files play like they did before jellyfin 10

I assume your using 1.5.0 for the app.  I have found that, no matter what x265 video is getting transcoded because of an issue with the way video profiles are identified.  I have a post about it here and also chatted with the developers about it.

Interestingly, when the x265 video gets transcoded, it takes the audio with it and my EAC3 audio is getting transcoded into AAC.

As for x264, I had issues with x264 getting transcoded into...wait for it....x264 lol.  That problem was solved by downgraded from server version 10.8.1 to 10.8.0.  I've also not had this problem with 10.8.3.

For now I've settled on server 10.8.3 via Docker and I'm running an old snapshot of the dev code prior to the transcoding fix being merged which messed with x265 profile stuff and I'm getting direct play on my devices.  It's not ideal and I hope they can fix the x265 stuff soon, but I am able to direct play my x265/x264 video with AC3, DTS AND EAC3 getting passed through to my receiver.

**Comment by lakerssuperman** [comment]
> I'm using 10.8.1 with a Roku Express 4k+ and it's playing back a BluRay disk via direct play (1080p, h264). Just deployed 10.8.3 to test against that and it also direct plays for me.
> 
> My issue is direct really seems to stutter :(

Is your Bluray rip using DTS audio?

**Comment by Sector14** [comment]
> Is your Bluray rip using DTS audio?

This post has some info on the BluRays I've tested with: https://github.com/jellyfin/jellyfin-roku/issues/541#issuecomment-1210439795 It's sounding like it may be a hw limitation on the roku of 10mbps on h264 (40mbps on h265).

I have no issue with direct play with those though, that's tested on 10.8.1 and 10.8.3. By "no issue" I mean it will direct play both audio and video (ignore the stuttering, that's another issue :P)

**Comment by lakerssuperman** [comment]
> > Is your Bluray rip using DTS audio?
> 
> This post has some info on the BluRays I've tested with: [#541 (comment)](https://github.com/jellyfin/jellyfin-roku/issues/541#issuecomment-1210439795) It's sounding like it may be a hw limitation on the roku of 10mbps on h264 (40mbps on h265).
> 
> I have no issue with direct play with those though, that's tested on 10.8.1 and 10.8.3. By "no issue" I mean it will direct play both audio and video (ignore the stuttering, that's another issue :P)

So I just tried playing my bluray rip of The Batman.  23,000 ish kb video bitrate. Jellyfin had to transcode the TrueHD, but it played without issue on my old Roku Ultra.

I only asked about DTS because the new Rokus seem to have issue with files with DTS audio if certain tags are missing from the mkv container and this playback has a noticeable stutter.

**Comment by rth9** [comment]
Since the 1.5 update on my 2020 Ultra, x265 stopped working. Some wouldn't load, others did the stutter for video, but I could hear the audio. I tried on the 2022 Ultra, same issue. I previously tried various combinations of changing the settings in Jellyfin web to try hardware decoding, transcoding, etc., that I could see, but nothing I tried seem to change anything.

What I did try tonight was change the 'Auto' values for video and audio in the Roku settings. I changed the video to 4K HDR 60 FPS and audio to Stereo. I don't think the video has any bearing and will switch it back to audio to test, and switching audio to 'Stereo" is less than ideal, but it will play all the x265/HEVC files that wouldn't play since the 1.5 update.

**Comment by kamanwu** [comment]
Server: 10.8.4
Media:
   container: mkv
   video: HEVC
   audio: AAC
   sub: SUBRIP


The media is being converted into a format that is compatible with the device that is playing the media.
Framerate: 107fps

11.0 Mbps TS H264 AAC

Reason for transcoding:
The video codec's profile is not supported

**Comment by kamanwu** [comment]
Just try the latest version.  Look this this issue is still there.
Based on: https://developer.roku.com/en-gb/docs/specs/media/streaming-specifications.md
HEVC (H.265) 4K video should be supported by Roku 4K capable devices.


A movie with video:
Title: CREATiVE - 720p - HEVC - SDR
Codec: HEVC
Profile: Main
Level: 93
Resolution: 1280x536
It does **DIRECT** play.


A movie with video:
Title: 4K HEVC SDR
Codec: HEVC
Profile: Main 10
Level: 150
Resolution: 3840x1600
It says:
Reason for transcoding:
The video codec's profile is not supported

**Comment by lakerssuperman** [comment]
> Just try the latest version. Look this this issue is still there. Based on: https://developer.roku.com/en-gb/docs/specs/media/streaming-specifications.md HEVC (H.265) 4K video should be supported by Roku 4K capable devices.

Yes, the HEVC profile support, unfortunately, hasn't been merged yet.  There is code in one of the PRs that corrects the transcoding issue.  Last I saw in the discussions they were hoping it would be merged and rolled out in a soonish update.  Running the PR, everything HEVC direct plays (1080p, 4K, HDR10) on my devices.
