### ISSUE TITLE
Support Continue Watching from Roku 11.5

### ISSUE THREAD

**Issue by candrews** [jellyfin-archive/jellyfin-roku-legacy#790]
**Is your feature request related to a problem? Please describe.**
Roku 11.5 has been released adding a new feature:
> Continue Watching: Designed to make streaming on Roku even more convenient, Continue Watching makes it easier than ever for users to resume watching TV shows and movies they were previously streaming. Located within What to Watch on the Roku Home Screen Menu, Continue Watching gives users a single location to jump back into the content they are watching, from a selection of streaming channels including HBO Max, Netflix, Paramount+, and The Roku Channel, with more channels to come.

-- https://newsroom.roku.com/news/2022/09/roku-launches-os-11-5-and-new-software-features-/m68s20xn-1662963775

I'd love to see the Jellyfin app support this feature.

**Describe the solution you'd like**
Jellyfin implements the Roku 11.5 Continue Watching feature.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by neilsb** [comment]
There's nothing about this (as yet) in the developer documentation, and their press release states specific channels that are included ... "with more to come".

I'm not saying that this will definitely not be possible in the future, but I suspect this is something that Roku will set up with the Channel Operators.  Because Jellyfin is self-hosted there is not a "public endpoint" that the Roku servers can query with user information to get the "Continue Watching" information, like they can do with streaming services, which they can then provide to the boxes/sticks.   In order for this to work Roku would need to query the endpoint from the app on each device, then the device itself would need to contact the local Jellyfin server and handle the results themselves.  

I personally don't see this happening in the near future, and this is the reason why we cannot integrate with the Roku OS Search functionality.   We would certainly be open to supporting it if it becomes technically feasible, but until then I'm afraid it's not something we can do.
