### ISSUE TITLE
Cannot get Extra Videos to show as options

### ISSUE THREAD

**Issue by frob** [jellyfin-archive/jellyfin-roku-legacy#830]
**Describe the bug**
Extra features do not show up as video options. I think this might be a regression.

As an example I have The Fellowship of the Ring Extended Edition named:

`/mnt/Media/Movies/The Lord of the Rings The Fellowship of the Ring (2001)/The Lord of the Rings The Fellowship of the Ring (2001) - Extended Edition Part 1.m4v`
`/mnt/Media/Movies/The Lord of the Rings The Fellowship of the Ring (2001)/The Lord of the Rings The Fellowship of the Ring (2001) - Extended Edition Part 2.m4v`

But in the Roku app I can only watch part 1.

**Expected behavior**

Ideally we would be able to watch Part 2 by selecting it as an option.

**Comment by jimdogx** [comment]
I just tested this with a sample video I created with 3 different versions.  It appears to work on the latest 1.6.1.  Are you seeing the version selection dropdown on the web client?

**Comment by frob** [comment]
In the web client I see another section labeled "Additional Parts" that I don't see in Roku. 

![image](https://user-images.githubusercontent.com/316176/202884382-bd3853d6-aa55-4c45-9fda-0508d2d1f16d.png)

Checking *another title* that has multiple versions I see a drop down with the multiple versions listed. Checking this title on the Roku does allow me to pick another version in the video options for the movie.

![image](https://user-images.githubusercontent.com/316176/202884246-7121b094-556f-444d-b178-a0af51c8e187.png)

**Comment by frob** [comment]
I am currently running `Version: 10.7.6` of Jellyfin.
I am running the latest version of the Roku client `1.6.1`

**Comment by jimdogx** [comment]
Looks like this has been reported before and got lost in the weeds: https://github.com/jellyfin/jellyfin-roku/issues/420 

I'm investigating.

**Comment by jimdogx** [comment]
@frob any chance you are comfortable with pulling a branch and running a developer version of the Roku client?  If so, can you test jimdogx:feature/jf-830-movie-additonal-parts and see if it works for you?

If none of what I said makes any sense, feel free to ignore my question 😄

**Comment by frob** [comment]
If you have a link to a developer guide, or how to set up a development environment, I would be comfortable with that. Would this require a dedicated roku device?

I found this link in the readme https://github.com/jellyfin/jellyfin-roku/blob/unstable/DEVGUIDE.md is that still accurate? I will have to purchase another roku device to test this. No word yet on if I will be able to do that any time soon.

**Comment by jimdogx** [comment]
You can use the same Roku you currently use.  It will install the developer version along side the released app.  Note you can only install one developer app on Roku at a time (shouldn't be an issue here).

The dev guide still works, but we've made it easier these days as every Pull Request now creates a build:

https://github.com/jellyfin/jellyfin-roku/actions/runs/3508850741

The following file on this☝️page is the actual build:

"Jellyfin-Roku-dev-d42479498a7b7fdb66925919b6b63176713a2ce2" 

You simply follow the Roku dev guide and upload this zip file via a web browser and test away 👍 

These are the steps to upload the above mentioned Zip file... instead of "Hello World" you'll be uploading Jellyfin 😄 
https://developer.roku.com/docs/developer-program/getting-started/hello-world.md

You can easily delete the developer build after you are done by simply hitting the "*" while the app is highlighted and then "Remove Channel"

**Comment by jimdogx** [comment]
Just to be clear, this will not affect your currently installed version of the Jellyfin app.  It will install a new channel called "Jellyfin Dev" on your Roku.  Also, if you do decide to follow the Roku dev instructions, you don't need a developer account or any of that.  I only linked to those instructions so you could see how to upload a build via the web browser.

If you need any help, you can always join us in the [Matrix](https://matrix.to/#/+jellyfin:matrix.org)

**Comment by frob** [comment]
I tested that build and it does show a section labeled "Additional Features" though it was hard to find.

This new section is below "Cast & Crew" and the "More like this" section. It should probably be above those other sections and labeled "Additional Parts" which is how the web client presents it.

Another bug I noticed with this was the screenshot isn't shown in a screen shot image style but rather if displays in a portrait style like the head shots and box art.
