### ISSUE TITLE
Roku 1.6 Access controls are broken. Leaking restricted search results.

### ISSUE THREAD

**Issue by VideoFX** [jellyfin-archive/jellyfin-roku-legacy#848]
**Describe the bug**
The search function is allowing users without access to libraries to see the results of the restricted libraries. However, on other apps such as web browser and android, the access controls are working as expected.

**To Reproduce**
Search for something you are not supposed to have access to.

Server:
Ubuntu 20.04
Jellyfin.Server 10.8.7.0

**Comment by VideoFX** [comment]
Maybe related to https://github.com/jellyfin/jellyfin/issues/8718 ?

**Comment by neilsb** [comment]
Looks like that may well be the same issue.   Roku search uses the /Search/Hints endpoint, whereas Web uses the Items/Artists/Person endpoint for searching, hence the different behaviours.

Restrictions to search/view/access content should be handled by the server as opposed to the clients, so we probably just need to wait for this to fixed in server.

**Comment by frob** [comment]
Not sure if this is related but content is also leaked when just browsing. A limited user will see teaser images for collections that they have no access to.

**Comment by 1hitsong** [comment]
Access controls and content are handled upstream from the server. These issues need to be opened there so they can be addressed.

https://github.com/jellyfin/jellyfin/issues

Just so we're all on the same page. The Roku app simply uses the API to get the data, the server is in charge of supplying it.

**Comment by VideoFX** [comment]
Thank you. Waiting for the fix to be released.
