### ISSUE TITLE
Movie screen glitches in and out

### ISSUE THREAD

**Issue by johnmmcgee** [jellyfin-archive/jellyfin-roku-legacy#863]
When going to the movie section, the posters blink on and off as does the background.

**Comment by 1hitsong** [comment]
This happens when the API requests posters in sizes that are larger than the screen.

Can you post a screenshot of the screen this happens on?

**Comment by johnmmcgee** [comment]
I dont think a screenshot would do it justice, as it just blinks.  It does not happen on the TV list, just on the movie list.

Anyway to pinpoint the offending posted?  This is rather annoying.

**Comment by 1hitsong** [comment]
Oh I've seen the blinking many times and am familiar with how the blink looks. I use the screenshots to know exactly what screen users are on so I know I'm looking at the correct spot.

You say the "movie list." Is that the first screen you get with clicking on the Movie Library?

**Comment by johnmmcgee** [comment]
Yes this is correct.  Upon clicking on Movies, i am met with the interface that shows all of the movie posters, and the wallpaper is generally the fan art based on the movie that is highlighted.

However, everything seems to blink as if its having a psychotic meltdown (possibly inducing one upon myself when trying to navigate to a movie! :D)

**Comment by 1hitsong** [comment]
"everything seems to blink as if its having a psychotic meltdown"

😄  Yep. That's the one. I'll try to recreate and see what I find.

**Comment by johnmmcgee** [comment]
awesome, let me know if i can provide any further information concerning this.  I would love to get this resolved.

**Comment by jimdogx** [comment]
This was supposed to be fixed by: https://github.com/jellyfin/jellyfin-roku/pull/605 

Totally bummed it did not fix it.  There is currently an issue with the server where some people are reporting the aspect ratio cannot be determined: 

https://github.com/jellyfin/jellyfin/issues/7617  
https://github.com/pdulvp/jellyfin-qnap/issues/28

Any chance you could look through both server and Roku logs and see if there are any clues?

**Comment by johnmmcgee** [comment]
anything in particular i should be looking for in the logs?

**Comment by jimdogx** [comment]
In the server logs anything with "[ERR]" or "Exception".  On the Roku side, anything with "ERROR".  But of course, if you see anything fishy at all, then share that as well 😄

**Comment by johnmmcgee** [comment]
Not certain how I would get log's from the roku side.

**Comment by jimdogx** [comment]
https://github.com/jellyfin/jellyfin-roku/blob/unstable/DEVGUIDE.md#bugcrash-reports

telnet roku-ip 8085

**Comment by johnmmcgee** [comment]
> https://github.com/jellyfin/jellyfin-roku/blob/unstable/DEVGUIDE.md#bugcrash-reports
> 
> telnet roku-ip 8085

connection refused.

**Comment by johnmmcgee** [comment]
Anything I can do to help move this along?

**Comment by 1hitsong** [comment]
Not really. Just need someone to find time to work on it.

**Comment by Dr-Evazan** [comment]
Not to be a pest (since you guys are doing great work) but is this still a thing? I've checked recently (on version 1.6) and am still seeing the "psychotic meltdown" mentioned previously. Thanks.

**Comment by 1hitsong** [comment]
Don't worry, It's still a thing and we haven't forgotten about it.

**Comment by johnmmcgee** [comment]
any movement on this?  It's really my only complaint with the current app.

**Comment by 1hitsong** [comment]
We only have 1 person in either the dev or QA team who has experienced this issue. I asked him if he's experienced it on the current unstable branch and he said no.

Are you able to help test the unstable branch and confirm?

**Comment by johnmmcgee** [comment]
I was able to install the dev version and I can confirm that the blinking no longer happens.  However, some posters do not seem to show up at this time.

I see the posters just fine under the web interface.

**Comment by 1hitsong** [comment]
That sounds like a separate issue than what this bug ticket was for. Open a new bug ticket and provide as much info as possible. What server version you're on, what kind of Roku you have, screenshots, etc. The more info the better so we can look into it.

It seems this bug is fixed in unstable, which will be released soon as 2.0.0. Marking closed.

You may also want to post this on the forum: https://forum.jellyfin.org/f-troubleshooting

There are a lot of great troubleshooters on there!
