### ISSUE TITLE
Unable to do anything with the app after installing and entering server account info.

### ISSUE THREAD

**Issue by nicxvan** [jellyfin-archive/jellyfin-roku-legacy#91]
**Describe the bug**
After installing the app on my roku I cannot view any media. When I click on tv shows it says this media type is not supported yet.
When I click on movies a gray screen with a green 1 shows up.

If I search for the title of a show it shows up. I cannot play the season though.

**To Reproduce**
Follow install steps from README
1. Go to TV shows
2. Click on TV Shows
3. See error

**Expected behavior**
I expect to see a list of tv shows and to be able to select a show, season / episode.

**Logs**
I don't know how to see logs.

**Screenshots**

**Additional context**

**Comment by KhelbenArunsun** [comment]
I've got the same problem, except that I don't have any problem playing movies. Host is Arch Linux 5.3.13 x86_64 GNU/Linux.

**Comment by bisby** [comment]
There were regressions with TV shows when a refactor was done, since some of the already broken (but slightly functional) stuff didn't translate over very well.

Movie library types should be just fine for now.

If you super need movies in the near term, you can revert back to commit b78094477c8e7294cd6c4c2f802117ec91bb30dc but even then tv shows were pretty sketchy for functionality

**Comment by KhelbenArunsun** [comment]
Yup, that works for now, just tried it today

**Comment by nicxvan** [comment]
Is there a roadmap? I'd really like to move off of roku media center and I'm willing to test.

**Comment by bisby** [comment]
Roadmap is "I fixed this tonight, and just made a PR" because my wife was upset about this as well.

This isn't particularly pretty, or fast. but it is what you might call "barely passable".

Thanks to everyone for voicing concerns about what features matter. :clinking_glasses: this has been a thing i've been meaning to get around to for a while, and feedback helped motivate me to stop being lazy and just solve it.

**Comment by nicxvan** [comment]
I just tried testing this, I rebuilt the app by running make install after pulling the latest code.

TV shows still says this media type is not supported.

**Comment by bisby** [comment]
The media type is definitely in master now (make sure youre back on master branch if you changed to the other test branch).

If things werent working you would get a crash or different error. If you are getting not implemented message then you haven't installed the new code.

**Comment by nicxvan** [comment]
Do I need to uninstall the app in order to install the newest?

I'm definitely on master, I checked the last commit it was your merge for pr 94

**Comment by bisby** [comment]
try `make deploy` instead. it cleans some stuff out before installing

**Comment by nicxvan** [comment]
It seems to be working, I had to reset the developer password, I can now see the shows. I'll test around a bit and open new issues if I find any.

Thanks!
