### ISSUE TITLE
TV Shows unplayed count not correct after applying filter

### ISSUE THREAD

**Issue by 1hitsong** [jellyfin-archive/jellyfin-roku-legacy#931]
Open TV Shows list. If you apply a filter, the unwatched count from the 1st series will get applied to the first series in the filtered view. The count is not recalculated/reapplied.

View All - Note 63 unplayed on 1st item and nothing on Buzzkill (indicating all are played)
![image](https://user-images.githubusercontent.com/3330318/209963219-9c5d9fd0-8372-4f66-ab40-3300f569734e.png)

Filtered by played - Note 63 now on Buzzkill instead of nothing.
![image](https://user-images.githubusercontent.com/3330318/209963240-87198cad-f61c-4373-9260-ab30e223e782.png)

**Comment by ApexArray** [comment]
Confirmed the occurs when applying a filter, but only affects series with no unwatched items. The issue also goes away if you back out of TV Shows and open it up again (with the filter still applied).

Since applying a filter re-uses existing SGnodes, the unplayed count is still visible from the previous item. We need to ensure `unplayedCount` and `unplayedEpisodeCount` nodes are set appropriately when `UnplayedItemCount` is 0 or invalid.

This code worked for me:
![image](https://user-images.githubusercontent.com/91706106/210156833-717ae30e-3cf5-460b-9ffc-2d1d2d68e678.png)
